{"name": "Создание заказа с одним цветом BLACK", "status": "passed", "description": "Проверка создания заказа с цветом BLACK", "steps": [{"name": "Создать заказ", "status": "passed", "parameters": [{"name": "payload", "value": "{'firstName': 'ljlecbmx', 'lastName': 'bwdotndr', 'address': 'pgmdmuniwx, 99 apt.', 'metroStation': '143', 'phone': '+79744246796', 'rentTime': 6, 'deliveryDate': '2024-12-31', 'comment': 'hxqiyvvnkytxxvr', 'color': ['BLACK']}"}], "start": 1761487149622, "stop": 1761487165522}, {"name": "Отменить заказ с трек-номером: 583931", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='qa-scooter.praktikum-services.ru', port=443): Max retries exceeded with url: /api/v1/orders/cancel (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254AB387890>, 'Connection to qa-scooter.praktikum-services.ru timed out. (connect timeout=None)'))\n", "trace": "  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\there\\Sprint_7\\api\\orders_api.py\", line 53, in cancel_order\n    return requests.put(ORDERS_CANCEL, json={\"track\": track_number})\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 130, in put\n    return request(\"put\", url, data=data, **kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 507, in send\n    raise ConnectTimeout(e, request=request)\n"}, "parameters": [{"name": "track_number", "value": "583931"}], "start": 1761487165522, "stop": 1761487187964}], "start": 1761487149622, "stop": 1761487187965, "uuid": "a3979532-4014-49fb-a316-f970a15dca9c", "historyId": "abe6d54ebc946625a16d263b8a1ca35a", "testCaseId": "abe6d54ebc946625a16d263b8a1ca35a", "fullName": "tests.test_order_create.TestOrderCreate#test_create_order_with_black_color", "labels": [{"name": "suite", "value": "Создание заказа"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestOrderCreate"}, {"name": "host", "value": "Astti-Legion"}, {"name": "thread", "value": "132044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_create"}]}