{"uuid": "4d12963f-b4ab-4baa-af84-a364b2167c01", "children": ["76dbe7ca-83bf-4a7a-90c6-a977c4a70aae"], "befores": [{"name": "created_courier", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='qa-scooter.praktikum-services.ru', port=443): Max retries exceeded with url: /api/v1/courier/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254AB387750>, 'Connection to qa-scooter.praktikum-services.ru timed out. (connect timeout=10)'))\n", "trace": "  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\there\\Sprint_7\\conftest.py\", line 36, in created_courier\n    login_response = CourierAPI.login_courier({\n        \"login\": courier_data[\"login\"],\n        \"password\": courier_data[\"password\"]\n    })\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\there\\Sprint_7\\api\\courier_api.py\", line 31, in login_courier\n    return requests.post(COURIER_LOGIN, json=payload, timeout=10)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 507, in send\n    raise ConnectTimeout(e, request=request)\n"}, "steps": [{"name": "Создать курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'mewcptkmef', 'password': 'epykagfutg', 'firstName': 'oewcrinbtz'}"}], "start": 1761487043668, "stop": 1761487044981}, {"name": "Логин курьера", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='qa-scooter.praktikum-services.ru', port=443): Max retries exceeded with url: /api/v1/courier/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254AB387750>, 'Connection to qa-scooter.praktikum-services.ru timed out. (connect timeout=10)'))\n", "trace": "  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\there\\Sprint_7\\api\\courier_api.py\", line 31, in login_courier\n    return requests.post(COURIER_LOGIN, json=payload, timeout=10)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 507, in send\n    raise ConnectTimeout(e, request=request)\n"}, "parameters": [{"name": "payload", "value": "{'login': 'mewcptkmef', 'password': 'epykagfutg'}"}], "start": 1761487044981, "stop": 1761487054996}], "start": 1761487043667, "stop": 1761487054998}], "start": 1761487043667, "stop": 1761487055065}